

REQUEST_ARGS_ERROR = "REQUEST_ARGS_ERROR"

AUTH_ACCESS_TOKEN_EXPIRE = "AUTH_ACCESS_TOKEN_EXPIRE"
AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED"

ACCOUNT_USERNAME_REPEAT = "ACCOUNT_USERNAME_REPEAT"
ACCOUNT_USERNAME_NOT_EXIST = "ACCOUNT_USERNAME_NOT_EXIST"
ACCOUNT_WRONG_PASSWORD = "ACCOUNT_WRONG_PASSWORD"
ACCOUNT_DISABLED = "ACCOUNT_DISABLED"

TOKEN_NOT_EXIST = "TOKEN_NOT_EXIST"
TOKEN_EXPIRE = "TOKEN_EXPIRE"

RESOURCE_NOFOUND = "RESOURCE_NOFOUND"


ERROR_SECRET_KEY = "ERROR_SECRET_KEY"